

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
    app.kubernetes.io/part-of: mistral-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mistral-inference-gateway
  namespaceSelector:
    matchNames:
      - mistral-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
    app.kubernetes.io/part-of: mistral-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm-server
  namespaceSelector:
    matchNames:
      - mistral-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dcgm-exporter-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
    app.kubernetes.io/part-of: mistral-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dcgm-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
      scrapeTimeout: 10s
