

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  
  name: model-pvc
  namespace: mistral-gateway   

  labels:
    app.kubernetes.io/name: model-provisioning
    app.kubernetes.io/component: persistentvolumeclaim
    app.kubernetes.io/part-of: mistral-gateway
    model: mistral-7b-instruct-v0.3

  annotations:
    
    volume.kubernetes.io/selected-node: "bound-to-model-gcs-pv"

spec:
  
  accessModes:
    - ReadOnlyMany

  
  resources:
    requests:
      storage: 50Gi

 
  storageClassName: ""

 
  volumeName: model-gcs-pv     