

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-sa
  namespace: mistral-gateway               

  labels:
    app.kubernetes.io/name: mistral-inference-gateway
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: mistral-gateway

  annotations:

    iam.gke.io/gcp-service-account: "fastapi-gsa@project-d9f9eda6-2e99-4916-a87.iam.gserviceaccount.com"


automountServiceAccountToken: false
